### ISSUE TITLE
Audible search gives no results now 

### ISSUE THREAD

**Issue by thepagal** [romanoh/Mp3tag-Repository#1]
As of today, I haven't been able to use the audible search at all. When I search for the book, I get results but whenever I select the book, it gives an error saying the search did not yield any matches (along those lines).

Tried on multiple books, tried redoing it over and over, etc. But no luck. Any ideas?

**Comment by romanoh** [comment]
Yes. They change the Asin.
go to line 128 and replace:

findline "\"productAsin\" value=\""
findinline "\"productAsin\" value=\""

with

findline "<input type=\"hidden\" name=\"asin\" value=\""
findinline "<input type=\"hidden\" name=\"asin\" value=\""


or get the file from my repository.

Let me now if it is ok now.

**Comment by thepagal** [comment]
It's fixed, thank you :)
