### ISSUE TITLE
Request to add Audiobook source from Itunes

### ISSUE THREAD

**Issue by PepperRobb97** [romanoh/Mp3tag-Repository#10]
Hello,
I'm so very very impressed by your work and I was wondering if you would be able to create something for Itunes? I have a large collection of m4b audiobooks (which I prefer for bookmarks and chapters) I am a PC user not a MAC user and unfortunately, Mp3tag has not made this easy for a coding illiterate person like me to be able to bring this information in. I don't want to download Itunes or even get an Itunes account. I have yet to see a decent MP3Tag source that pulls information for audiobooks and since you are updating everything else out there and doing an awesome job from what I can see, I was wondering if you would be willing to do this for me and the MP3Tag community that also uses audiobooks? 

Some of the tags I would be looking for, and I'm sure others are as well, would be Title, Artist, Narrator, Allbum, Series, Series #, Track, Genre or Mediatype, Abridged or Unabridged version, Release Year or year, ISBN OR AISN, PUBLISHER, COPYRIGHT, COVER, DESCRIPTION OR COMMENT
Thanks so very much

**Comment by romanoh** [comment]
Hi
Thank you for your words. 
I will look into it in my spare time.
but why do you want to use this, if per example the Audiobooks.com source tag, has all the metadata you can  ever need(it works whit all kind of audiofiles)?

**Comment by PepperRobb97** [comment]
does audio books.com have the same tags for iTunes? I'm trying to make this as simple as possible without going into various programs to pull information. I have actions setup in MP3TAG. First I drop an audio book file in MP3TAG, and choose a source (preferably iTunes but right now I cannot get any of iTunes sources to work with my audio books) Right now Audible seems to be the best source for me for information on the audio books I listen to as I'm US Based. After I choose the correct book from Audible, I built a few actions that adjust the tags on the files the way I want them quickly with little to no effort on my part and then I can move on to the next file. At this point, I have over 1TB of Audiobooks that I need to tag appropriately. Lots of them are Series books and I know I need to adjust filenames as well so a lot of work needs to be done in general on all of it. 

This is alot to ask and I'm very very well aware of that. Like I said, my coding is pretty non-existant. But if you think that it's similar to the audiobooks.com source I can certainly give it a shot. Do you by any chance have a listing of the tags for iTunes for 2022? I have searched and cannot find them. But maybe I didn't look hard enough. Maybe I can just substitute the tags in MP3TAG that I have currently (most likely the ID3 ones) with those used by iTunes. I will also see if I can put a request for this on the website. This wouldn't be an issue if I owned or used Mac products. However, I don't use or own any. Only PC and android which is why I'm running into this issue. If I had MP3TAG for MAC I could just use the tagging for that easily....

**Comment by romanoh** [comment]
Sorry i meant Audible.com, almost every audiobook is in there and the same metadata, if not, i have others sources for the metadada form other providers.
I have seen the itunes and they have few audiobooks, so i think it is not worth it to make one.
Like i said, use the Audible Source, its the best one.
Also you can see my actions i have in here(and how i handle the series) to make your options.

**Comment by PepperRobb97** [comment]
I appreciate it. Right now I am using the Audible one extensively. I'll download yours and take a look at all your stuff here on the site to see what I can find regarding series etc everything. I appreciate you taking the time to help me with this. Sorry to bother you but you have been a wonderful help!!!
