### ISSUE TITLE
Multiple # Author/Artist and # Narrator on storytel, also a fix for # Description

### ISSUE THREAD

**Issue by Dolkis** [romanoh/Mp3tag-Repository#11]
Here is an add to the script if you have more then one authors and narrator.
Also, dhje Description is not working as intended. I fixed it but I dont know if its optimised.

	# Author/Artist
	outputto "Artist"
	findline "authors"
	findinline "href="
	findinline ">"
	sayuntil "<"

	outputto "Artist"
	moveline 1
	if ","
       say "; "
	findline "authors"
	findinline "href="
	findinline ">"
	sayuntil "<"
	else
	say ""
	gotoline 1
	endif

	outputto "Artist"
	moveline 1
	if ","
      say "; "
	findline "authors"
	findinline "href="
	findinline ">"
	sayuntil "<"
	else
	say ""
	gotoline 1
	endif

	outputto "Artist"
	moveline 1
	if ","
      say "; "
	findline "authors"
	findinline "href="
	findinline ">"
	sayuntil "<"
	else
	say ""
	gotoline 1
	endif

-----------------------------
	# Narrator
	outputto "Composer"
	findline "narrators"
	findinline "href="
	findinline ">"
	sayuntil "<"

	outputto "Composer"
	moveline 1
	if ","
      say "; "
	findline "narrators"
	findinline "href="
	findinline ">"
	sayuntil "<"
	else
	say ""
	gotoline 5
	endif

	outputto "Composer"
	moveline 1
	if ","
      say "; "
	findline "narrators"
	findinline "href="
	findinline ">"
	sayuntil "<"
	else
	say ""
	gotoline 5
	endif

	outputto "Composer"
	moveline 1
	if ","
      say "; "
	findline "narrators"
	findinline "href="
	findinline ">"
	sayuntil "<"
	else
	say ""
	gotoline 5
	endif

	outputto "Composer"
	moveline 1
	if ","
      say "; "
	findline "narrators"
	findinline "href="
	findinline ">"
	sayuntil "<"
	else
	say ""
	gotoline 5
	endif
----------------------------------
	
	

	# Description
	outputto "Comment"
	findline "book-description"
	findinline "><p>"
	replace "<article class=\"book-description svelte-2y4p89\">" ""
	replace "</p>" " "
	replace "<p>" " "
	replace "<br>" " "
	sayuntil "</article>"

**Comment by romanoh** [comment]
ok i will add it, thank you for this.

**Comment by romanoh** [comment]
something is wrong. before i add your improvements i must solve the year:
![imagem](https://user-images.githubusercontent.com/5342223/167263117-2e0cca4f-48b6-4fea-8b1c-3be1ad4c091c.png)

**Comment by Dolkis** [comment]
I can check the script, I think I know what the problem is. I did some changes due to I use the swedish site for Storytel.

I can send you the whole SE storytel if you want to add it.

(Will do it tonight, I need to lay my kids to bed).

I just need to ask one thing, do you know if there is a working linux docker for mp3tag? >.<

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: romanoh ***@***.***>
Skickat: Saturday, May 7, 2022 6:23:40 PM
Till: romanoh/Mp3tag ***@***.***>
Kopia: Dolkis ***@***.***>; Author ***@***.***>
Ämne: Re: [romanoh/Mp3tag] Multiple # Author/Artist and # Narrator on storytel, also a fix for # Description (Issue #11)


something is wrong. before i add your improvements i must solve the year:
[imagem]<https://user-images.githubusercontent.com/5342223/167263117-2e0cca4f-48b6-4fea-8b1c-3be1ad4c091c.png>

**Comment by romanoh** [comment]
I am sorry i uses windows, ask in the mp3tag forums.

I have already fixed the year issue, but somehow the replace instruction is not working, if i made : replace "dd" " ", it goes to the first char.

**Comment by Dolkis** [comment]
# Description
outputto "Comment"
findline "book-description"
findinline "><p>"
replace "<article class=\"book-description svelte-2y4p89\">" ""
replace "</p>" " "
replace "<p>" " "
replace "<br>" " "
sayuntil "</article>"


this one is working like a charm.
Tho I cant get the Author /  Narrator to work on the english version of storytel.

Its working when there are more authors, but fails when comming to descriptions, IF there are only one author.

________________________________
Från: romanoh ***@***.***>
Skickat: den 7 maj 2022 18:43
Till: romanoh/Mp3tag ***@***.***>
Kopia: Dolkis ***@***.***>; Author ***@***.***>
Ämne: Re: [romanoh/Mp3tag] Multiple # Author/Artist and # Narrator on storytel, also a fix for # Description (Issue #11)


I am sorry i uses windows, ask in the mp3tag forums.

I have already fixed the year issue, but somehow the replace instruction is not working, if i made : replace "dd" " ", it goes to the first char.

**Comment by romanoh** [comment]
I will look into it, very  few people give feedback about my web sources, thank you for your ideia and code.
If the Swedish web source works for you good, aim glad i helped.
