### ISSUE TITLE
Mofibo.com

### ISSUE THREAD

**Issue by Njur** [romanoh/Mp3tag-Repository#12]
Hi I was very happy when I found your mofibo src tool, but it doesn't work.
It searches but afterwards just gives empty tagresult even when it's on Mofibo.com only thing it finds is cover.
Can you help please?

**Comment by romanoh** [comment]
Hi there, its not my src tool, but if i have time i will look into it.

**Comment by Njur** [comment]
Oh okay thanks. It's very nice of you. Hope it's not too much trouble.
Best regards Peter

fre. 11. nov. 2022 13.10 skrev romanoh ***@***.***>:

**Comment by romanoh** [comment]
Please use the Json version, i have altered. I think it works.

**Comment by Njur** [comment]
Thanks for the help , I've answered you in the mp3tag forum
