### ISSUE TITLE
Search returns empty results

### ISSUE THREAD

**Issue by scottgshin** [romanoh/Mp3tag-Repository#13]
![image](https://user-images.githubusercontent.com/13341486/206865894-62e3c18d-5e4e-4b9b-8d08-f7d6853cc2f1.png)
All searches by artist and album return no results.

**Comment by romanoh** [comment]
Did you updated? there is a new version now [v.03.12.2022]. Please download/past it in your file, and let me know.

**Comment by scottgshin** [comment]
That is the version I am running and it is still not returning any matches.

**Comment by scottgshin** [comment]
Sorry, did a comparison and found that I had an older version. Updated to the newest and it populates with matches and works correctly. Thank you
