### ISSUE TITLE
Audible.com Not Returning Any Results

### ISSUE THREAD

**Issue by Webby2687** [romanoh/Mp3tag-Repository#15]
Hello,

I had been using the Audible.com search by Album function and it was working great for months. Recently this has stopped working and after finding this post on the MP3Tag forums it said to come here and download the latest .src file. I downloaded a zip file, and extracted, copied and pasted into my appData folder (in the right sub-folders). Now after running the search no matter how vague I put the search conditions no results are being returned.

I searched for 'Brandon Sanderson The Well of Ascension' and it returned no results:
![image](https://user-images.githubusercontent.com/47880626/210855607-8f0472ff-184c-4697-ac8e-c89a9c8ea3a2.png)

![image](https://user-images.githubusercontent.com/47880626/210855622-bd6f08b0-5a47-48b6-9cff-b3dd6f89d9d4.png)

Interestingly just searching by Album and putting in just the author name (Brandon Sanderson) I get the same results. I then tried just the book/album name and it also returned no results.

I then tried just searching with the Audible.com file name option instead of the album search and I see 3 results, the top one is the .com version (correct version with the correct duration), the middle one is the UK version and the bottom is Spanish. I noticed that instead of the book/album name I'm getting the category for the .com result:
![image](https://user-images.githubusercontent.com/47880626/210855838-37c50c06-5482-4f10-9a09-09ebd2ffa502.png)

When I click Next on this album no results appear, and clicking the 'This album on Audible.Com' it takes me to a generic search page showing it did not find the book. 

For reference here is the URL of the book/album that I expected the search to find: https://www.audible.com/pd/The-Well-of-Ascension-Audiobook/B002V5GLQ4?ref=a_library_t_c5_libItem_B002V5GLQ4&pf_rd_p=80765e81-b10a-4f33-b1d3-ffb87793d047&pf_rd_r=NR1QZ7GHDA3X8BVHTDT2&pageLoadId=AzoFggD0ulTPGhn9&creativeId=4ee810cf-ac8e-4eeb-8b79-40e176d0a225

Edit: I tried this with multiple files/albums as well with the same result, so it does not seem isolated to this album.

Thank you in advance for any assistance!

**Comment by romanoh** [comment]
I Will reply this weekend i am away from home.

**Comment by romanoh** [comment]
@Webby2687 the search is working for me:
![imagem](https://user-images.githubusercontent.com/5342223/211079596-db78dd9b-b15f-42de-a03a-67cda6716505.png)

the right version is 03.12.2022: https://github.com/romanoh/Mp3tag/blob/master/data/sources/Audible.com%23Search%20by%20Album.src

just copy the text and replace it in "Audible.com#Search by Album.src"
are you using Mac?

**Comment by Webby2687** [comment]
@romanoh Thank you. I ended up just deciding to do fresh install and after uninstall & reinstall with the new scripts everything is working again. Thank you for your help!
