### ISSUE TITLE
can vgmdb only pull japanese title tracks instead ?

### ISSUE THREAD

**Issue by namper77** [romanoh/Mp3tag-Repository#16]
i only want to pull japanese title, it still work when album only has few song, but it has 20 or more.
it gonna take lots of time to edit it

**Comment by romanoh** [comment]
will look into it soon

**Comment by namper77** [comment]
> will look into it soon

Thank you for considering my request

**Comment by romanoh** [comment]
did you try the solutions that are in the mp3tag forum: per example:

[https://community.mp3tag.de/t/ws-vgmdb/9731/122?u=romano](https://community.mp3tag.de/t/ws-vgmdb/9731/122?u=romano)

or this one: 

[https://community.mp3tag.de/t/ws-vgmdb-extended/59822/9?u=romano](https://community.mp3tag.de/t/ws-vgmdb-extended/59822/9?u=romano)

**Comment by namper77** [comment]
it worked with second link, about first link the json doesnt work.
thanks for your support
