### ISSUE TITLE
Garbage in some tags on VGMdb.

### ISSUE THREAD

**Issue by Lichtenshtein** [romanoh/Mp3tag-Repository#18]
I presume there have been changes on the site again since last script update, as the parser is capturing garbage from the web page in these fields:

ARTIST, COMPOSER, ALBUMARTIST

HTML version.

Link for verification
https://vgmdb.net/album/122155

**Comment by romanoh** [comment]
I see try to fix soon, thank you,

**Comment by romanoh** [comment]
I see you use the html version, why don't use the JSON version its mutch better. i stopped working in the html version as i made the Json version.

![Model](https://i.imgur.com/ZSgvSW4.png)

**Comment by Lichtenshtein** [comment]
> why don't use the JSON version its mutch better

1) How to choose romaji in JSON version?
2) No ARTIST, COMPOSER fields...
3) Periodic problems with accessing vgmdb.info - it loads on the third attempt, sometimes for some reason it is not available at all. It was like that yesterday when i was testing.

**Comment by romanoh** [comment]
Try this version:  https://community.mp3tag.de/t/ws-vgmdb-extended/59822

**Comment by Lichtenshtein** [comment]
I have both.

> Try this version: https://community.mp3tag.de/t/ws-vgmdb-extended/59822

This one is great too, but

- No romaji for the first link i tested it on (my first post)
- All artist credits go into one field and one line like this:

INVOLVEDPEOPLE: Artist:NITTY GRITTY;Vocal:Rino Kishimori;Keyboard:Rino Kishimori;Drums:Akio Imaizumi;Percussion:Akio Imaizumi;Bass:Tooru Kasuya;Guitar:Hitoshi Asou;Chorus:NITTY GRITTY;Words:Yumi Morita, Yuu Kureko, Shizuka Psyche, Izumi;Music:Tetsushi Ryu, Akira Odakura <...>

and

VGMDB_ALL_CREDITS: Artist:NITTY GRITTY;Vocal:Rino Kishimori;Keyboard:Rino Kishimori;Drums:Akio Imaizumi;Percussion:Akio Imaizumi;Bass:Tooru Kasuya;Guitar:Hitoshi Asou;Chorus:NITTY GRITTY;Words:Yumi Morita, Yuu Kureko, Shizuka Psyche, Izumi;Music:Tetsushi Ryu, Akira Odakura <...>


Your HTML script seems more useful. JSON version shows this:
```
Server connection error: vgmdb.info

> 500: Internal Server Error
```

Ah, I see. The result overall is different from album to album. Apparently i was unlucky with the very first album i tested. A rather inconvenient source this VGMDB is...
