### ISSUE TITLE
Storytel for french version

### ISSUE THREAD

**Issue by baloodusudouest** [romanoh/Mp3tag-Repository#19]
Hi,

I try the storytel tagger, but it's not working with the french version
I try to modify the .src files to change to https://www.storytel.com/fr/fr/search-
I try with this book https://www.storytel.com/fr/fr/books/magic-charly-tome-3-justice-soit-faite-2584074
I can have the cover, but no other information.

Do you know how i can do?

Thanks

**Comment by romanoh** [comment]
You try for the api version: https://www.storytel.com/api/fr/search.action?q=%s
just change the links (not tested)

edit: i think they change the html code, will look to it later.

**Comment by baloodusudouest** [comment]
thanks because with the link change it not work

**Comment by IstadR** [comment]
No result on Storytel, Norwegian, English and Swedish searches. Gets results if i put the api-link directly in browser.

**Comment by romanoh** [comment]
Will look into it
