### ISSUE TITLE
Cetegories (Genre)

### ISSUE THREAD

**Issue by romanoh** [romanoh/Mp3tag-Repository#2]
AUDIBLE: i have noticed that when a book dont have Categories (genre) (there is lot of books without categories, especial series parts) it stops the process because it dont have an "if" part, this days i did not had time to update my script, will soon i think.
![imagem](https://user-images.githubusercontent.com/5342223/92510870-6cf4e080-f204-11ea-9cd2-4665d2b47e11.png)

**Comment by seanap** [comment]
I was able to get this fixed here https://github.com/seanap/Audible.com-Search-by-Album/commit/280ae0a720955074bbd084d97afc529bbbc838c4
