### ISSUE TITLE
html markup in a few fields

### ISSUE THREAD

**Issue by Garash2k** [romanoh/Mp3tag-Repository#20]
Used Mp3tag to tag [this album](https://vgmdb.net/album/118930)

It worked pretty well! There is however a bunch of html markup in a few fields: ARTIST, COMPOSER and ALBUM ARTIST

![image](https://github.com/romanoh/Mp3tag/assets/6396368/c73a220e-3276-4a13-a46d-2366b1bfd4b3)

**Comment by romanoh** [comment]
what version of the script did you use?

**Comment by Garash2k** [comment]
The one in this repo with a commit from 3 months ago, I used github's "Download ZIP" button under "Code."

**Comment by romanoh** [comment]
The web sources from vgmdb, are older:
![image](https://i.imgur.com/mzHxYq3.png)

**Comment by Garash2k** [comment]
Well I've been using those yes, are you saying there are newer versions elsewhere?

**Comment by romanoh** [comment]
The Json version i think its ok.
but you can try this other source, that was based on mine, and was improved: [https://community.mp3tag.de/t/ws-vgmdb-extended/59822](url)
