### ISSUE TITLE
Audiobooks.com tag source not working

### ISSUE THREAD

**Issue by BDaddyG** [romanoh/Mp3tag-Repository#21]
Good day,

Just found your scripts and attempted to use the Audiobooks.com tag source.  Unfortunately, it didn't work (reported no matching results found).  

Manually looking at Audobooks.com I was able to find the book.

I looked over the script and made changes to get it work and return results.  As I'm not familiar with the Github/Git process, (forking and making a pull request I believe is what is needed), can I send you the changes for your review?  Or post them here?

My changes are based on Audiobooks.com#Search by Title[v.20.10.2023].src

Thanks for the scripts!

**Comment by romanoh** [comment]
put it here, i will fix it. thank you.

**Comment by romanoh** [comment]
you can try the new version i have uploaded here.

**Comment by cerinawithasea** [comment]
this is getting a forbidden answer
403 error connecting to server
