### ISSUE TITLE
not an issue got scribd/everand to work

### ISSUE THREAD

**Issue by cerinawithasea** [romanoh/Mp3tag-Repository#22]
![image](https://github.com/romanoh/Mp3tag/assets/71559155/57c9a9e5-9c0f-460f-b098-98647e295cd8)
Theses were all blank
`# ######################################################################
# Mp3tag web source for scribd.com, Created by Romano.
#
# Copy this file to your sources directory at
# %APPDATA%\Mp3tag\data\sources
#
# Changes: https://github.com/romanoh/Mp3tag-Repository
#
# [2023-09-23]
# NEW: First version
#
# ######################################################################

[Name]=everand.com [v.05.10.2023]
[BasedOn]=everand.com
[IndexUrl]=https://www.everand.com/search/query?query=%s
[AlbumUrl]=https://www.everand.com/audiobook/
[WordSeparator]=%20
[IndexFormat]=%_preview%|%_url%|% ↓ Title%|% ↓ Author%
#remove everything inside ()
[SearchBy]=Enter Album Name||$regexp(%album%,'\([^)]*\)',,1)||%s
[Encoding]=url-utf-8
[UserAgent]=1

[ParserScriptIndex]=...
# ###################################################################
#					I  N  D  E  X
# ###################################################################
#DebugWriteInput "C:\Users\xxxx\Desktop\scribd.html"
#Debug "ON" "C:\Users\xxxxx\Desktop\index_scrib.txt"

json "ON"

json_select_object "results"
json_select_object "audiobooks"
json_select_object "content"

json_foreach "documents"

		# Preview (no column, only for preview)
		json_select "book_preview_url"
		SayRest
		Say "|"

		json_select "id"
		SayRest
		Say "|"

		json_select "title"
		SayRest
		Say "|"

		json_select "author"
		json_select "name"
		SayRest
		saynewline
			
json_foreach_end
json_unselect_object

################################################################################
#                        ADJUST TAG INFORMATION DIALOG                         #
################################################################################
[ParserScriptAlbum]=...

## Comment/uncomment for debugging purposes:
#DebugWriteInput "C:\Users\xxxx\Desktop\scribd_album_debug.html"
#Debug "ON" "C:\Users\xxxx\Desktop\scribd_album_debug.txt"

# Use the json inside the html
FindLine "type=\"application/ld+json\">"
FindinLine "type=\"application/ld+json\">"

# Language
OutputTo "language"
findinline "\"inLanguage\":\""
sayuntil "\""

# Isbn
OutputTo "isbn"
findinline "\"isbn\":\""
sayuntil "\""

#Album Title
outputto "Album"
findinline "\"name\":\""
sayuntil "\""

#Comment
outputto "Comment"
findinline "\"description\":\""
regexpreplace "<[^>]+>" ""
sayuntil "\""

# Cover
outputto "Coverurl"
findinline "\"image\":\""
sayuntil "\""

# Author
outputto "artist_1"
findinline "\"author\""
findinline "\"name\":\""
sayuntil "\""

outputto "artist_2"
findinline "},{\"@type\":\"Person\",\"name\":\"" 1 1
sayuntil "\""

outputto "artist_3"
findinline "},{\"@type\":\"Person\",\"name\":\"" 1 1
sayuntil "\""

IfNotOutput "artist_2"
	gotoline 1
	FindLine "type=\"application/ld+json\">"
	FindinLine "type=\"application/ld+json\">"
else
endif

outputto "artist"
sayoutput "artist_1"
IfOutput "artist_2"
	say "/"
	sayoutput "artist_2"
else
endif
IfOutput "artist_3"
	say "/"
	sayoutput "artist_3"
else
endif

# Clean temp 
set "artist_1"
set "artist_2"
Set "artist_3"

# narrator
outputto "composer_1"
findinline "\"readBy\"" 1 1
findinline "\"name\":\"" 1 1
sayuntil "\""

outputto "composer_2"
findinline "},{\"@type\":\"Person\",\"name\":\"" 1 1
sayuntil "\""

outputto "composer_3"
findinline "},{\"@type\":\"Person\",\"name\":\"" 1 1
sayuntil "\""

outputto "composer"
IfNotOutput "composer_1"
else
	sayoutput "composer_1"
endif

IfOutput "composer_2"
	say "/"
	sayoutput "composer_2"
else
endif
IfOutput "composer_3"
	say "/"
	sayoutput "composer_3"
else
endif

# Clean temp 
set "composer_1"
set "composer_2"
Set "composer_3"

IfNotOutput "composer_2"
	gotoline 1
	FindLine "type=\"application/ld+json\">"
	FindinLine "type=\"application/ld+json\">"
else
endif

#Publisher
outputto "publisher"
findinline "\"publisher\":\""
sayuntil "\""

#Publisher
outputto "year"
findinline "\"datePublished\":\""
saynextnumber

#Duration
#outputto "duration"
#findinline "\"duration\":\""
#replace "PT" ""
#sayuntil "\""

# Set Artist = Albumartist
outputto "albumartist"
sayoutput "Artist"

# Set Audible Album URL
outputto "WWWAUDIOFILE"
sayoutput "CurrentUrl"

# Set Comment to DESCRIPTION for better MP4 support
outputto "DESCRIPTION"
sayoutput "Comment"`

**Comment by romanoh** [comment]
Thank you, but its better if you can past it to a site like [https://pastebin.com/](https://pastebin.com/) , to get it proper formated, so i can update the web source using your changes.

**Comment by cerinawithasea** [comment]
ok sorry i will try, ive never done this before

**Comment by cerinawithasea** [comment]
tbc i kinda understand the language but not really, im like a tourist Im sure somebody can make it better 
just whatever i did they work now
everand
https://pastebin.com/Tva1rRNC
this one i did awhile ago, back when i was on the mp3tag board begging for the scribd source lol
GoodReads
https://pastebin.com/Napj6tcd
I hope this helps somehow, and that i did this right
thanks
Cerina
edit- typos, i've never typed anything without a typo
 more thing these work for me on mac also

**Comment by cerinawithasea** [comment]
one thing maybe it would be so cool if i could fill in all the boxes, im afraid of messing with it to much and ruining it

**Comment by cerinawithasea** [comment]
![image](https://github.com/romanoh/Mp3tag/assets/71559155/66ddbcf7-77d3-4b07-af11-6cb49b66aa4b)
just noticed the parentheses in comment
the tags on the left i filled with the preview showing, others didn't do  that

 
![image](https://github.com/romanoh/Mp3tag/assets/71559155/4eabcbf9-81e5-4bb0-8c3c-574f33263e48)

**Comment by romanoh** [comment]
For the everand.com, thank you for pointing for the new website. I have update it.
For goodreads, i will add it to the github, and improve it when i can.

You asked for improvements, and i will do it, and let you know.

**Comment by romanoh** [comment]
For Everand, you can try my new version (for series there are not many info on the site):

[https://github.com/romanoh/Mp3tag/blob/master/data/sources/Everand.com%23Search%20by%20%26Album%20Json%20Version.src](https://github.com/romanoh/Mp3tag/blob/master/data/sources/Everand.com%23Search%20by%20%26Album%20Json%20Version.src)

**Comment by cerinawithasea** [comment]
Oh i am so excited,my internet is down right now i just have my phone and my ipad. As soon as its up I will be back "with bells on" 
Lol is that the saying?
Thank you a billion bunches, this made today better
