### ISSUE TITLE
Libro.fm not returning data.

### ISSUE THREAD

**Issue by andithelibrarian** [romanoh/Mp3tag-Repository#24]
Hi. Thank you for this. I am having an issue with Libro.fm not returning anything when I search. All of my audiobooks come from Libro.fm, so I know that they are on the website. I'm sure they've just changed something on their website, but I'm not sure what. Thanks for any help.

**Comment by andithelibrarian** [comment]
Hi. It is working now. I don't know why I couldn't get it to work a couple of days ago. Maybe Libro.fm was having issues with their site at the time. That said, about 50% of the time when I let it search by both author and title, which is the default, it returns no data, and I have to go back and delete the author name from the search. Is it possible to alter the script so that it only searches for the title?

**Comment by romanoh** [comment]
try this:
change this line:
`[SearchBy]=%artist% $regexp(%album%,'[- ]+cd ?\d+$',,1)`

to this line:
`[SearchBy]=$regexp(%album%,'[- ]+cd ?\d+$',,1)`
