### ISSUE TITLE
VGMDB - Can track names not be pulled from either the HTML or the JSON?

### ISSUE THREAD

**Issue by Tenome** [romanoh/Mp3tag-Repository#4]
Hello, first time using your script (very useful!). I was just wondering because I never get any track names whenever I pull up the album in MP3Tag. Is it something on VGMDB's end that makes fetching the names difficult?

Thanks.

**Comment by romanoh** [comment]
Sometimes They change 
the html so the scrape wont work, will try to fix it this week

**Comment by Tenome** [comment]
Thanks!

**Comment by romanoh** [comment]
Have you tried the JSON version?, it works for me (except the artist, as i am waiting for the original author of the JSON to make the change).

![imagem](https://user-images.githubusercontent.com/5342223/95761145-cdfc5200-0ca3-11eb-8d38-8bcd7990253c.png)

**Comment by romanoh** [comment]
Please try the HTML let me now.

**Comment by Tenome** [comment]
HTML seems to work now. JSON gives me blank results like before, but I can live with that if HTML works. Thanks!

https://puu.sh/GCgDj/89485857d6.png

**Comment by romanoh** [comment]
@Tenome no problem in the album in Japanese tracks, just change the line 177 `json_select "English"` to `json_select "Japanese"`

**Comment by romanoh** [comment]
> 
> 
> @Tenome no problem in the album in Japanese tracks, just change the line 177 `json_select "English"` to `json_select "Japanese"`

This is no longer necessary as the script now pulls all the languages.
