### ISSUE TITLE
[VGMdb] Album image previews are broken

### ISSUE THREAD

**Issue by TheShadowRunner** [romanoh/Mp3tag-Repository#5]
As VGMdbAlbumParser.inc expects .jpg or .png images but VGMdb recently switched to .webp.
Hoping a fix is possible.
Thanks for your dedication in keeping these scripts going !

**Comment by romanoh** [comment]
Hello

the VGMdb is working for me, the Json and normal version, can you give an album example?
also the file extension does not matter as the parser gets the full link.




![imagem](https://user-images.githubusercontent.com/5342223/104711415-3fbbc000-5719-11eb-8635-5f2c773f820f.png)

**Comment by TheShadowRunner** [comment]
Here's an exemple :
https://vgmdb.net/album/107313

More info directly from the horse's mouth:
"album cover filetype is determined by whatever type the original image was", meaning if the format uploaded was jpg, it'll remain jpg [and work with the script]. 
But if a user uploads a webp, vgmdb will use it as-is (= my exemple), in this case it breaks the script.
So they didn't switch to webp completely but rather added support for it, I was mistaken.

Thanks for your support.

**Comment by romanoh** [comment]
You are right. i first must see if mp3tag suports webp. 
edit:
it does not only : 
![imagem](https://user-images.githubusercontent.com/5342223/104733495-ad2a1980-5736-11eb-99b2-c3c6aec158a7.png)

i see what can i do

Edit:
The ID3 standard recommends png and jpg for best compatibility.

**Comment by romanoh** [comment]
I cannot do it by changing  the .webp to .jpg, in the script, it gives an error.
So or mp3tag change support(made a post in forum) or you have to make it by hand: download the file and change the extension.

**Comment by romanoh** [comment]
This is now suported:
[https://community.mp3tag.de/t/support-for-webp-image-previews/51592/11?u=romano](https://community.mp3tag.de/t/support-for-webp-image-previews/51592/11?u=romano)

**Comment by TheShadowRunner** [comment]
Yes I saw Florian added support. But without auto-convertion to PNG or JPG it doesn't make much sense ?

**Comment by romanoh** [comment]
i did some test in the link you give and it woks.
the auto conversion i think is another thing.

**Comment by TheShadowRunner** [comment]
Thanks for your feedback, apparently mp3tag is able to convert webp to jpg/png after all ? (how?) but it won't do it automatically. 
Or is the conversion something that is done at your level on the Source script ?

**Comment by romanoh** [comment]
I think there is no conversion, if you use the mp3tag software it gets the  .webp file, and it saves it to the audio tags.
and if you save it next to the audio file it stays  .webp. It is one more file image suportedd: 
![imagem](https://user-images.githubusercontent.com/5342223/113937191-b0421c80-97f0-11eb-8031-6ecb6293247d.png)

**Comment by TheShadowRunner** [comment]
Understood. The goal was being able to see webp image previews so this "issue" is fixed, thank you!
