### ISSUE TITLE
Storytel

### ISSUE THREAD

**Issue by Dolkis** [romanoh/Mp3tag-Repository#6]
Something have happened to the Storytel site.

The english version works perfect. But when I change it to she swedish version I made from you file.
I know get an error (> 404: Not Found).

I dont know what the problem might be...

**Comment by Dolkis** [comment]
okey... I did foun out what the problem is...
Sorytel have changed thiere site on the swedish one. Probobly the english site will follow soon.

view-source:https://www.storytel.com/se/sv/books/ett-ljus-i-m%C3%B6rkret-4802

view-source:https://www.storytel.com/in/en/books/137191-Test-Drive

The swedish site did function last week. Then it did look like the english one.

**Comment by romanoh** [comment]
Thank you for the information.
what exactly was the change?

**Comment by Dolkis** [comment]
Here we have the swedish HTML site:
https://imgur.com/hSWIj9Z

And here we have the EN HTML site:
https://imgur.com/B3DmxGj


The swedish one did look like the english one, the only change I made was how to find the book name, author and narrotar.
