### ISSUE TITLE
audible

### ISSUE THREAD

**Issue by evafans** [romanoh/Mp3tag-Repository#7]
I found that audible search result doesn’t contain narrotors， and it doesn‘t fetches images.

**Comment by romanoh** [comment]
I will look to it soon.

**Comment by romanoh** [comment]
It is working for me:
![imagem](https://user-images.githubusercontent.com/5342223/131726194-a6d58307-ccfb-4054-aadf-4b4de6119699.png)

did you use the Audible.com#Search by Album.src  ?

what did you search for?

**Comment by evafans** [comment]
I guess maybe there is something wrong with mine.

**Comment by romanoh** [comment]
If you like to develop more, i will try to help.
