### ISSUE TITLE
VGMdb not working

### ISSUE THREAD

**Issue by palla89** [romanoh/Mp3tag-Repository#8]
Hi there, I tried all the VGMdb related plug-in but even if it does not give me any error, the window that should contain informations is empty. Can you help me?

**Comment by romanoh** [comment]
I will take a look later.

**Comment by palla89** [comment]
Thank you very very much mate!!!!! If you need anything for tests or such, I'm available!

**Comment by palla89** [comment]
I would like to help you, is there any trick to debug / test it easily?

**Comment by romanoh** [comment]
I Will fix it this weekend.

All the info is here: https://help.mp3tag.de/main_online.html

In this case go to the debbuging secction.

Its easy i am not a programer like you, still i learn it.

**Comment by romanoh** [comment]
I had time to see, and the script is working fine(the normal and the Json version):

If any particular album is not working, let me know.

![image](https://user-images.githubusercontent.com/5342223/143451380-d0843180-80a1-4415-96a4-dc30b8cca8f0.png)

**Comment by palla89** [comment]
Uh, I should try again, do you use the JSON or album? I tried with both but nothing.. the album I was trying is this: https://vgmdb.net/album/51690 
Is this giving results to you?

**Comment by romanoh** [comment]
Both are working:

![image](https://user-images.githubusercontent.com/5342223/143451917-7ea5044c-4eba-41ed-a4d2-3ded3a2c3ab7.png)

**Comment by palla89** [comment]
This is so strange, I'm sorry I let you lose precious time :( I'm checking it again in a few minutes and tell you if it works

**Comment by romanoh** [comment]
No problem, let me know.

**Comment by palla89** [comment]
It works!!!! I somehow mistakenly added the src files, the plugin were showing but it wasn't loading fine. My bad! 
Thank you for your support and for the great work!!
